### ISSUE TITLE
Comparing version from required string

### ISSUE THREAD

**Issue by tiagofrancafernandes** [z4kn4fein/php-semver#1]
Hi, I want to know if this package has a method to check if it meets the requirements passed by a string, like:

```php
$myVersion = '1.2.3';
$requiredVersion = '^1.0';
```
The result of check must returns true, and this too:

```php
$myVersion = '2.2.3';
$requiredVersion = '^1.0|^2.0';
```

**Comment by tiagofrancafernandes** [comment]
Just close this if works now.
I'm available if you need help.

**Comment by z4kn4fein** [comment]
Hi @tiagofrancafernandes, currently, checking versions against version ranges is not supported. It might be implemented in the future, but for now, it's not on my roadmap.

**Comment by z4kn4fein** [comment]
Hi @tiagofrancafernandes, I've decided to implement constraint validation in [v2.0.0](https://github.com/z4kn4fein/php-semver/releases/tag/v2.0.0). 
The documentation is available [here](https://github.com/z4kn4fein/php-semver#constraints). 

Let me know if you have questions, also, I appreciate any feedback!
